### ISSUE TITLE
Add ipython-notebook to `statsseminar` environment

### ISSUE THREAD

**Issue by lgbouma** [adrn/PrincetonStatsSeminar#1]
Else manual install is necessary for running notebooks.

**Comment by adrn** [comment]
Should be `jupyter notebook` these days. I thought that came with anaconda? In any case, updated the environment file -- thanks.

**Comment by lgbouma** [comment]
Could be that I'm using a miniconda install? Regardless. Thanks!

**Comment by adrn** [comment]
Ah, that could be it! Hopefully everyone leaves it to the last minute and will get the latest env file :)
